// Written by Ismael Heredia in the year 2016

package sistema.ui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import sistema.dao.UsuarioDAO;

public class FormHome extends javax.swing.JFrame {

    /**
     * Creates new form FormHome
     */
    ApplicationContext context = new ClassPathXmlApplicationContext("Spring.xml");
    private String username;

    public FormHome() {
        initComponents();

    }

    public void cargarDatos(String username_now) {
        this.username = username_now;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        status = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmOpciones = new javax.swing.JMenu();
        jmiProductos = new javax.swing.JMenuItem();
        jmiProveedores = new javax.swing.JMenuItem();
        jmiUserAdmin = new javax.swing.JMenuItem();
        jmEstadisticas = new javax.swing.JMenu();
        jmiListarProductos = new javax.swing.JMenuItem();
        jmiGenerarGraficos = new javax.swing.JMenuItem();
        jmCuenta = new javax.swing.JMenu();
        jmiCambiarUsuario = new javax.swing.JMenuItem();
        jmiCambiarPass = new javax.swing.JMenuItem();
        jmExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        status.setText("Programa cargado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(status)
                .addGap(0, 308, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(status)
        );

        jmOpciones.setText("Opciones");

        jmiProductos.setText("Productos");
        jmiProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProductosActionPerformed(evt);
            }
        });
        jmOpciones.add(jmiProductos);

        jmiProveedores.setText("Proveedores");
        jmiProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProveedoresActionPerformed(evt);
            }
        });
        jmOpciones.add(jmiProveedores);

        jmiUserAdmin.setText("Usuarios");
        jmiUserAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUserAdminActionPerformed(evt);
            }
        });
        jmOpciones.add(jmiUserAdmin);

        jMenuBar1.add(jmOpciones);

        jmEstadisticas.setText("Estadisticas");
        jmEstadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmEstadisticasMouseClicked(evt);
            }
        });

        jmiListarProductos.setText("Listar productos");
        jmiListarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarProductosActionPerformed(evt);
            }
        });
        jmEstadisticas.add(jmiListarProductos);

        jmiGenerarGraficos.setText("Generar graficos");
        jmiGenerarGraficos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGenerarGraficosActionPerformed(evt);
            }
        });
        jmEstadisticas.add(jmiGenerarGraficos);

        jMenuBar1.add(jmEstadisticas);

        jmCuenta.setText("Cuenta");

        jmiCambiarUsuario.setText("Cambiar nombre de usuario");
        jmiCambiarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCambiarUsuarioActionPerformed(evt);
            }
        });
        jmCuenta.add(jmiCambiarUsuario);

        jmiCambiarPass.setText("Cambiar contraseña");
        jmiCambiarPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCambiarPassActionPerformed(evt);
            }
        });
        jmCuenta.add(jmiCambiarPass);

        jMenuBar1.add(jmCuenta);

        jmExit.setText("Salir");
        jmExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmExitMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 246, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProductosActionPerformed
        FormProductos ventana = new FormProductos();
        ventana.setVisible(true);
    }//GEN-LAST:event_jmiProductosActionPerformed

    private void jmExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmExitMouseClicked
        int resultado = JOptionPane.showConfirmDialog(this,
                "¿ Desea salir del programa ?",
                "Salir", JOptionPane.YES_NO_CANCEL_OPTION);
        if (resultado == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jmExitMouseClicked

    private void jmiProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProveedoresActionPerformed
        FormProveedores ventana = new FormProveedores();
        ventana.setVisible(true);
    }//GEN-LAST:event_jmiProveedoresActionPerformed

    private void jmiCambiarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCambiarUsuarioActionPerformed
        FormCambiarUsuario ventana = new FormCambiarUsuario();
        ventana.cargarDatos(username);
        ventana.setVisible(true);
    }//GEN-LAST:event_jmiCambiarUsuarioActionPerformed

    private void jmiCambiarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCambiarPassActionPerformed
        FormCambiarContraseña ventana = new FormCambiarContraseña();
        ventana.cargarDatos(username);
        ventana.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jmiCambiarPassActionPerformed

    private void jmiUserAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUserAdminActionPerformed
        FormUsuarios ventana = new FormUsuarios();
        ventana.setVisible(true);
    }//GEN-LAST:event_jmiUserAdminActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        UsuarioDAO usuarioDAO = (UsuarioDAO) context.getBean("UsuarioDAO");
        if (usuarioDAO.es_admin(username)) {
            jmiUserAdmin.setEnabled(true);
        } else {
            jmiUserAdmin.setEnabled(false);
        }

    }//GEN-LAST:event_formWindowOpened

    public void cargarReporte(String reporte) {
        /*
         Conexion conexion_now = new Conexion();

         conexion_now.abrir();

         try {
         JasperReport reporteJasper = JasperCompileManager.compileReport(reporte);
         JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, null, conexion_now.retornar());
         JasperViewer.viewReport(mostrarReporte, false);

         } catch (Exception ex) {
         Logger.getLogger(FormHome.class.getName()).log(Level.SEVERE, null, ex);
         }

         conexion_now.cerrar();
         */
    }

    private void jmEstadisticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmEstadisticasMouseClicked
        //
    }//GEN-LAST:event_jmEstadisticasMouseClicked

    private void jmiListarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarProductosActionPerformed
        //cargarReporte("C:\\Users\\Test\\Documents\\NetBeansProjects\\sistema\\src\\Reportes\\ReporteListaProductos.jrxml");
    }//GEN-LAST:event_jmiListarProductosActionPerformed

    private void jmiGenerarGraficosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGenerarGraficosActionPerformed
        //cargarReporte("C:\\Users\\Test\\Documents\\NetBeansProjects\\sistema\\src\\Reportes\\ReporteGrafico.jrxml");
    }//GEN-LAST:event_jmiGenerarGraficosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jmCuenta;
    private javax.swing.JMenu jmEstadisticas;
    private javax.swing.JMenu jmExit;
    private javax.swing.JMenu jmOpciones;
    private javax.swing.JMenuItem jmiCambiarPass;
    private javax.swing.JMenuItem jmiCambiarUsuario;
    private javax.swing.JMenuItem jmiGenerarGraficos;
    private javax.swing.JMenuItem jmiListarProductos;
    private javax.swing.JMenuItem jmiProductos;
    private javax.swing.JMenuItem jmiProveedores;
    private javax.swing.JMenuItem jmiUserAdmin;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
