package sistema.entity;
// Generated 20-ene-2017 14:35:32 by Hibernate Tools 4.3.1



/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer idProducto;
     private Proveedores proveedores;
     private String nombreProducto;
     private String descripcion;
     private Integer precio;
     private String fechaRegistro;

    public Productos() {
    }

    public Productos(Proveedores proveedores, String nombreProducto, String descripcion, Integer precio, String fechaRegistro) {
       this.proveedores = proveedores;
       this.nombreProducto = nombreProducto;
       this.descripcion = descripcion;
       this.precio = precio;
       this.fechaRegistro = fechaRegistro;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }
    public String getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(String fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }




}


