Sistema\Bundle\Entity\Proveedores:
    type: entity
    table: null
    repositoryClass: Sistema\Bundle\Repository\ProveedoresRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 255
            column: nombre
        direccion:
            type: string
            length: 255
        telefono:
            type: integer
        fechaRegistro:
            type: string
            length: 255
            column: fecha_registro
    lifecycleCallbacks: {  }
