Sistema\Bundle\Entity\Usuarios:
    type: entity
    table: null
    repositoryClass: Sistema\Bundle\Repository\UsuariosRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 255
        clave:
            type: string
            length: 255
        idTipo:
            type: integer
        fechaRegistro:
            type: string
            length: 255
            column: fecha_registro
    lifecycleCallbacks: {  }
