<?php

namespace Sistema\Bundle\Repository;

/**
 * Tipo_UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
