Sistema\Bundle\Entity\Productos:
    type: entity
    table: null
    repositoryClass: Sistema\Bundle\Repository\ProductosRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombreProducto:
            type: string
            length: 255
            column: nombre_producto
        descripcion:
            type: string
            length: 255
        precio:
            type: integer
        idProveedor:
            type: integer
            column: id_proveedor
        fechaRegistro:
            type: string
            length: 255
            column: fecha_registro
    lifecycleCallbacks: {  }
