// Written By Ismael Heredia in the year 2016
package Vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;

public class FormHome extends javax.swing.JFrame {

    /**
     * Creates new form FormHome
     */
    private ArrayList notasMatematica;
    private ArrayList notasFisica;
    private ArrayList notasQuimica;
    private ArrayList notasLengua;
    private ArrayList notasGeografia;

    public FormHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpOptions = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblTexto = new javax.swing.JLabel();
        txtEntrada = new javax.swing.JTextField();
        lblSalida = new javax.swing.JLabel();
        txtSalida = new javax.swing.JTextField();
        btnReverseString = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblMatematica = new javax.swing.JLabel();
        lblFisica = new javax.swing.JLabel();
        lblQuimica = new javax.swing.JLabel();
        lblLengua = new javax.swing.JLabel();
        lblGeografia = new javax.swing.JLabel();
        txtNotaMatematica = new javax.swing.JTextField();
        txtNotaFisica = new javax.swing.JTextField();
        txtNotaQuimica = new javax.swing.JTextField();
        txtNotaLengua = new javax.swing.JTextField();
        txtNotaGeografia = new javax.swing.JTextField();
        btnAgregarNotaMatematica = new javax.swing.JButton();
        btnAgregarNotaFisica = new javax.swing.JButton();
        btnAgregarNotaQuimica = new javax.swing.JButton();
        btnAgregarNotaLengua = new javax.swing.JButton();
        btnAgregarNotaGeografia = new javax.swing.JButton();
        btnPromedioMatematica = new javax.swing.JButton();
        btnPromedioFisica = new javax.swing.JButton();
        btnPromedioQuimica = new javax.swing.JButton();
        btnPromedioLengua = new javax.swing.JButton();
        btnPromedioGeografia = new javax.swing.JButton();
        btnLimpiarMatematica = new javax.swing.JButton();
        btnLimpiarFisica = new javax.swing.JButton();
        btnLimpiarQuimica = new javax.swing.JButton();
        btnLimpiarLengua = new javax.swing.JButton();
        btnLimpiarGeografia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mmOutput = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejercicios");
        setName("FormHome"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblTexto.setText("Texto : ");

        lblSalida.setText("Salida : ");

        btnReverseString.setText("Reverse String");
        btnReverseString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReverseStringActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSalida)
                            .addComponent(lblTexto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEntrada)
                            .addComponent(txtSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btnReverseString, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTexto)
                    .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalida)
                    .addComponent(txtSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnReverseString)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        tpOptions.addTab("Reverse", jPanel1);

        lblMatematica.setText("Matematica : ");

        lblFisica.setText("Fisica : ");

        lblQuimica.setText("Quimica : ");

        lblLengua.setText("Lengua : ");

        lblGeografia.setText("Geografia : ");

        txtNotaLengua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNotaLenguaActionPerformed(evt);
            }
        });

        btnAgregarNotaMatematica.setText("Agregar");
        btnAgregarNotaMatematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNotaMatematicaActionPerformed(evt);
            }
        });

        btnAgregarNotaFisica.setText("Agregar");
        btnAgregarNotaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNotaFisicaActionPerformed(evt);
            }
        });

        btnAgregarNotaQuimica.setText("Agregar");
        btnAgregarNotaQuimica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNotaQuimicaActionPerformed(evt);
            }
        });

        btnAgregarNotaLengua.setText("Agregar");
        btnAgregarNotaLengua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNotaLenguaActionPerformed(evt);
            }
        });

        btnAgregarNotaGeografia.setText("Agregar");
        btnAgregarNotaGeografia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNotaGeografiaActionPerformed(evt);
            }
        });

        btnPromedioMatematica.setText("Promedio");
        btnPromedioMatematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromedioMatematicaActionPerformed(evt);
            }
        });

        btnPromedioFisica.setText("Promedio");
        btnPromedioFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromedioFisicaActionPerformed(evt);
            }
        });

        btnPromedioQuimica.setText("Promedio");
        btnPromedioQuimica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromedioQuimicaActionPerformed(evt);
            }
        });

        btnPromedioLengua.setText("Promedio");
        btnPromedioLengua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromedioLenguaActionPerformed(evt);
            }
        });

        btnPromedioGeografia.setText("Promedio");
        btnPromedioGeografia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromedioGeografiaActionPerformed(evt);
            }
        });

        btnLimpiarMatematica.setText("Limpiar");
        btnLimpiarMatematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarMatematicaActionPerformed(evt);
            }
        });

        btnLimpiarFisica.setText("Limpiar");
        btnLimpiarFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFisicaActionPerformed(evt);
            }
        });

        btnLimpiarQuimica.setText("Limpiar");
        btnLimpiarQuimica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarQuimicaActionPerformed(evt);
            }
        });

        btnLimpiarLengua.setText("Limpiar");
        btnLimpiarLengua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarLenguaActionPerformed(evt);
            }
        });

        btnLimpiarGeografia.setText("Limpiar");
        btnLimpiarGeografia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarGeografiaActionPerformed(evt);
            }
        });

        mmOutput.setColumns(20);
        mmOutput.setRows(5);
        jScrollPane1.setViewportView(mmOutput);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblQuimica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNotaQuimica, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblMatematica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNotaMatematica, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnAgregarNotaMatematica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPromedioMatematica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiarMatematica))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnAgregarNotaQuimica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPromedioQuimica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiarQuimica))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblGeografia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNotaGeografia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarNotaGeografia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPromedioGeografia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiarGeografia))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblFisica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNotaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarNotaFisica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPromedioFisica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiarFisica))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblLengua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNotaLengua, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarNotaLengua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPromedioLengua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiarLengua)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatematica)
                    .addComponent(txtNotaMatematica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarNotaMatematica)
                    .addComponent(btnPromedioMatematica)
                    .addComponent(btnLimpiarMatematica))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFisica)
                    .addComponent(txtNotaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarNotaFisica)
                    .addComponent(btnPromedioFisica)
                    .addComponent(btnLimpiarFisica))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuimica)
                    .addComponent(txtNotaQuimica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarNotaQuimica)
                    .addComponent(btnPromedioQuimica)
                    .addComponent(btnLimpiarQuimica))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLengua)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNotaLengua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregarNotaLengua)
                        .addComponent(btnPromedioLengua)
                        .addComponent(btnLimpiarLengua)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeografia)
                    .addComponent(txtNotaGeografia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarNotaGeografia)
                    .addComponent(btnPromedioGeografia)
                    .addComponent(btnLimpiarGeografia))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tpOptions.addTab("Notas", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        tpOptions.addTab("Enteros", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        tpOptions.addTab("Factorial", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpOptions)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReverseStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReverseStringActionPerformed
        if ("".equals(txtEntrada.getText())) {
            JOptionPane.showMessageDialog(this, "Ingrese texto");
        } else {
            String entrada = txtEntrada.getText();
            String salida = new StringBuilder(entrada).reverse().toString();
            txtSalida.setText(salida);
        }
    }//GEN-LAST:event_btnReverseStringActionPerformed

    private void txtNotaLenguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotaLenguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotaLenguaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        notasMatematica = new ArrayList();
        notasFisica = new ArrayList();
        notasQuimica = new ArrayList();
        notasLengua = new ArrayList();
        notasGeografia = new ArrayList();
    }//GEN-LAST:event_formWindowOpened

    private int calcularPromedio(String tipo) {

        int promedio = 0;

        try {
            ArrayList notas = new ArrayList();

            if ("matematica".equals(tipo)) {
                notas.addAll(notasMatematica);
            }
            if ("fisica".equals(tipo)) {
                notas.addAll(notasFisica);
            }
            if ("quimica".equals(tipo)) {
                notas.addAll(notasQuimica);
            }
            if ("lengua".equals(tipo)) {
                notas.addAll(notasLengua);
            }
            if ("geografia".equals(tipo)) {
                notas.addAll(notasGeografia);
            }

            int total = 0;

            for (int i = 0; i < notas.size(); i++) {
                int nota = (int) notas.get(i);
                total = total + nota;
            }

            promedio = total / notas.size();
        } catch (Exception e) {
            //
        }
        return promedio;
    }

    private void btnAgregarNotaMatematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNotaMatematicaActionPerformed
        if ("".equals(txtNotaMatematica.getText())) {
            JOptionPane.showMessageDialog(this, "Ingrese nota de Matematica");
        } else {
            int nota = Integer.parseInt(txtNotaMatematica.getText());
            notasMatematica.add(nota);
            mmOutput.append("Nota : " + txtNotaMatematica.getText() + " agregado en Matematica\n");
        }
    }//GEN-LAST:event_btnAgregarNotaMatematicaActionPerformed

    private void btnLimpiarMatematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarMatematicaActionPerformed
        mmOutput.append("Notas de Matematica borradas\n");
        notasMatematica.clear();
    }//GEN-LAST:event_btnLimpiarMatematicaActionPerformed

    private void btnPromedioMatematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromedioMatematicaActionPerformed
        mmOutput.append("Promedio de Matematica : " + calcularPromedio("matematica") + "\n");
    }//GEN-LAST:event_btnPromedioMatematicaActionPerformed

    private void btnAgregarNotaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNotaFisicaActionPerformed
        if ("".equals(txtNotaFisica.getText())) {
            JOptionPane.showMessageDialog(this, "Ingrese nota de Fisica");
        } else {
            int nota = Integer.parseInt(txtNotaFisica.getText());
            notasFisica.add(nota);
            mmOutput.append("Nota : " + txtNotaFisica.getText() + " agregado en Fisica\n");
        }
    }//GEN-LAST:event_btnAgregarNotaFisicaActionPerformed

    private void btnAgregarNotaQuimicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNotaQuimicaActionPerformed
        if ("".equals(txtNotaQuimica.getText())) {
            JOptionPane.showMessageDialog(this, "Ingrese nota de Quimica");
        } else {
            int nota = Integer.parseInt(txtNotaQuimica.getText());
            notasQuimica.add(nota);
            mmOutput.append("Nota : " + txtNotaQuimica.getText() + " agregado en Quimica\n");
        }
    }//GEN-LAST:event_btnAgregarNotaQuimicaActionPerformed

    private void btnAgregarNotaLenguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNotaLenguaActionPerformed
        if ("".equals(txtNotaLengua.getText())) {
            JOptionPane.showMessageDialog(this, "Ingrese nota de Lengua");
        } else {
            int nota = Integer.parseInt(txtNotaLengua.getText());
            notasLengua.add(nota);
            mmOutput.append("Nota : " + txtNotaLengua.getText() + " agregado en Lengua\n");
        }
    }//GEN-LAST:event_btnAgregarNotaLenguaActionPerformed

    private void btnAgregarNotaGeografiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNotaGeografiaActionPerformed
        if ("".equals(txtNotaGeografia.getText())) {
            JOptionPane.showMessageDialog(this, "Ingrese nota de Geografia");
        } else {
            int nota = Integer.parseInt(txtNotaGeografia.getText());
            notasGeografia.add(nota);
            mmOutput.append("Nota : " + txtNotaGeografia.getText() + " agregado en Geografia\n");
        }
    }//GEN-LAST:event_btnAgregarNotaGeografiaActionPerformed

    private void btnPromedioFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromedioFisicaActionPerformed
        mmOutput.append("Promedio de Fisica : " + calcularPromedio("fisica") + "\n");
    }//GEN-LAST:event_btnPromedioFisicaActionPerformed

    private void btnPromedioQuimicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromedioQuimicaActionPerformed
        mmOutput.append("Promedio de Quimica : " + calcularPromedio("quimica") + "\n");
    }//GEN-LAST:event_btnPromedioQuimicaActionPerformed

    private void btnPromedioLenguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromedioLenguaActionPerformed
        mmOutput.append("Promedio de Lengua : " + calcularPromedio("lengua") + "\n");
    }//GEN-LAST:event_btnPromedioLenguaActionPerformed

    private void btnPromedioGeografiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromedioGeografiaActionPerformed
        mmOutput.append("Promedio de Geografia : " + calcularPromedio("geografia") + "\n");
    }//GEN-LAST:event_btnPromedioGeografiaActionPerformed

    private void btnLimpiarFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFisicaActionPerformed
        mmOutput.append("Notas de Fisica borradas\n");
        notasFisica.clear();
    }//GEN-LAST:event_btnLimpiarFisicaActionPerformed

    private void btnLimpiarQuimicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarQuimicaActionPerformed
        mmOutput.append("Notas de Quimica borradas\n");
        notasQuimica.clear();
    }//GEN-LAST:event_btnLimpiarQuimicaActionPerformed

    private void btnLimpiarLenguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarLenguaActionPerformed
        mmOutput.append("Notas de Lengua borradas\n");
        notasLengua.clear();
    }//GEN-LAST:event_btnLimpiarLenguaActionPerformed

    private void btnLimpiarGeografiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarGeografiaActionPerformed
        mmOutput.append("Notas de Geografia borradas\n");
        notasGeografia.clear();
    }//GEN-LAST:event_btnLimpiarGeografiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarNotaFisica;
    private javax.swing.JButton btnAgregarNotaGeografia;
    private javax.swing.JButton btnAgregarNotaLengua;
    private javax.swing.JButton btnAgregarNotaMatematica;
    private javax.swing.JButton btnAgregarNotaQuimica;
    private javax.swing.JButton btnLimpiarFisica;
    private javax.swing.JButton btnLimpiarGeografia;
    private javax.swing.JButton btnLimpiarLengua;
    private javax.swing.JButton btnLimpiarMatematica;
    private javax.swing.JButton btnLimpiarQuimica;
    private javax.swing.JButton btnPromedioFisica;
    private javax.swing.JButton btnPromedioGeografia;
    private javax.swing.JButton btnPromedioLengua;
    private javax.swing.JButton btnPromedioMatematica;
    private javax.swing.JButton btnPromedioQuimica;
    private javax.swing.JButton btnReverseString;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFisica;
    private javax.swing.JLabel lblGeografia;
    private javax.swing.JLabel lblLengua;
    private javax.swing.JLabel lblMatematica;
    private javax.swing.JLabel lblQuimica;
    private javax.swing.JLabel lblSalida;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JTextArea mmOutput;
    private javax.swing.JTabbedPane tpOptions;
    private javax.swing.JTextField txtEntrada;
    private javax.swing.JTextField txtNotaFisica;
    private javax.swing.JTextField txtNotaGeografia;
    private javax.swing.JTextField txtNotaLengua;
    private javax.swing.JTextField txtNotaMatematica;
    private javax.swing.JTextField txtNotaQuimica;
    private javax.swing.JTextField txtSalida;
    // End of variables declaration//GEN-END:variables
}
