//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public int id_producto { get; set; }
        public string nombre_producto { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> precio { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public string fecha_registro { get; set; }
    
        public virtual proveedores proveedores { get; set; }
    }
}
