package Vista;

import Clases.ThreadEjecutar;
import java.util.List;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;

public class FormHome extends javax.swing.JFrame {

    /**
     * Creates new form FormHome
     */
    Thread thread;
    List<ThreadEjecutar> listaThreads;

    public FormHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsole = new javax.swing.JTextArea();
        btnStartThread = new javax.swing.JButton();
        btnStopThread = new javax.swing.JButton();
        btnStartThreads = new javax.swing.JButton();
        btnStopThreads = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejercicio Threads");
        setName("frmEjercicioThreads"); // NOI18N
        setResizable(false);

        txtConsole.setColumns(20);
        txtConsole.setRows(5);
        jScrollPane1.setViewportView(txtConsole);

        btnStartThread.setText("Start Thread");
        btnStartThread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartThreadActionPerformed(evt);
            }
        });

        btnStopThread.setText("Stop Thread");
        btnStopThread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopThreadActionPerformed(evt);
            }
        });

        btnStartThreads.setText("Start Threads");
        btnStartThreads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartThreadsActionPerformed(evt);
            }
        });

        btnStopThreads.setText("Stop Threads");
        btnStopThreads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopThreadsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStopThread, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnStopThreads, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStartThread, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnStartThreads, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStartThread)
                    .addComponent(btnStartThreads))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStopThread)
                    .addComponent(btnStopThreads))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartThreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartThreadActionPerformed
        JOptionPane.showMessageDialog(this, "Thread Iniciado", "Ejercicio Threads", 1);
        thread = new ThreadEjecutar("uno", txtConsole);
        thread.start();
    }//GEN-LAST:event_btnStartThreadActionPerformed

    private void btnStopThreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopThreadActionPerformed
        JOptionPane.showMessageDialog(this, "Thread Detenido", "Ejercicio Threads", 1);
        thread.stop();
    }//GEN-LAST:event_btnStopThreadActionPerformed

    private void btnStartThreadsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartThreadsActionPerformed
        JOptionPane.showMessageDialog(this, "Threads Iniciados", "Ejercicio Threads", 1);

        listaThreads = Collections.synchronizedList(new ArrayList<ThreadEjecutar>());

        for (int i = 1; i <= 5; i++) {
            Thread thread2 = new ThreadEjecutar(String.valueOf(i), txtConsole);
            listaThreads.add((ThreadEjecutar) thread2);
        }

        for (int i = 0; i < listaThreads.size(); i++) {
            Thread thread_loaded = (Thread) listaThreads.get(i);
            thread_loaded.start();
        }
    }//GEN-LAST:event_btnStartThreadsActionPerformed

    private void btnStopThreadsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopThreadsActionPerformed
        JOptionPane.showMessageDialog(this, "Threads Detenidos", "Ejercicio Threads", 1);
        for (int i = 0; i < listaThreads.size(); i++) {
            Thread thread_loaded = (Thread) listaThreads.get(i);
            thread_loaded.stop();
        }
    }//GEN-LAST:event_btnStopThreadsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartThread;
    private javax.swing.JButton btnStartThreads;
    private javax.swing.JButton btnStopThread;
    private javax.swing.JButton btnStopThreads;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtConsole;
    // End of variables declaration//GEN-END:variables
}
