//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedores
    {
        public proveedores()
        {
            this.productos = new HashSet<productos>();
        }
    
        public int id_proveedor { get; set; }
        public string nombre_empresa { get; set; }
        public string direccion { get; set; }
        public Nullable<int> telefono { get; set; }
        public string fecha_registro_proveedor { get; set; }
    
        public virtual ICollection<productos> productos { get; set; }
    }
}
