# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cambiarpassword_cambiarusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_producto',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombre_empresa',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='tipousuario',
            old_name='nombre_tipo',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_usuario',
            new_name='nombre',
        ),
    ]
