services:
#    sistema.example:
#        class: Sistema\Bundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  sistema.seguridad:
      class: Sistema\Bundle\Services\Seguridad
      arguments: ["@doctrine.orm.entity_manager","@session"]

  sistema.conexion:
      class: Sistema\Bundle\Services\Conexion
      arguments: ["@doctrine.orm.entity_manager","@session"]

  sistema.funciones:
      class: Sistema\Bundle\Services\Funciones
      arguments: []