# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170530_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buscador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_buscar', models.CharField(max_length=150)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
