# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170531_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambiarPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=150)),
                ('clave', models.CharField(max_length=150)),
                ('nueva_clave', models.CharField(max_length=150)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CambiarUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=150)),
                ('nuevo_usuario', models.CharField(max_length=150)),
                ('clave', models.CharField(max_length=150)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
